-- MySQL Script generated by MySQL Workbench
-- Sun Oct 13 14:18:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suppliers` (
  `SupplierID` INT(10) NULL,
  `SupplierName` VARCHAR(255) NULL,
  `SupplierContactName` VARCHAR(255) NULL,
  `SupplierContactLastName` VARCHAR(45) NULL,
  `Address` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `Phone` INT(15) NULL,
  `Website` VARCHAR(255) NULL,
  PRIMARY KEY (`SupplierID`),
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `ISBN` INT(13) NOT NULL,
  `Title` VARCHAR(255) NULL,
  `AuthorFirstName` VARCHAR(255) NULL,
  `AuthorLastName` VARCHAR(255) NULL,
  `Publisher` VARCHAR(255) NULL,
  `PublicationDate` DATE NULL,
  `Genre` VARCHAR(255) NULL,
  `Language` VARCHAR(255) NULL,
  `Price` DECIMAL NULL,
  `QuantityInStock` INT(10) NULL,
  `QuantityOnOrder` INT(10) NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IncomingOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IncomingOrder` (
  `PurchaseID` INT(10) NOT NULL,
  `SupplierID` INT(10) NOT NULL,
  `ISBN` INT(13) NOT NULL,
  `DatePlaced` DATE NULL,
  `PurchaseStatus` VARCHAR(255) NULL,
  PRIMARY KEY (`PurchaseID`),
  INDEX `fk_IncomingOrder_Supplier1_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `fk_IncomingOrder_Supplier1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `mydb`.`Suppliers` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IncomingOrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IncomingOrderItem` (
  `ISBN` INT(13) NOT NULL,
  `PurchaseID` INT(10) NOT NULL,
  `SupplierID` INT(10) NULL,
  `Quantity` INT(10) NULL,
  PRIMARY KEY (`PurchaseID`),
  INDEX `fk_IncomingOrderItem_Books1_idx` (`ISBN` ASC) VISIBLE,
  INDEX `fk_IncomingOrderItem_IncomingOrder1_idx` (`PurchaseID` ASC) VISIBLE,
  CONSTRAINT `fk_IncomingOrderItem_Books1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `mydb`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IncomingOrderItem_IncomingOrder1`
    FOREIGN KEY (`PurchaseID`)
    REFERENCES `mydb`.`IncomingOrder` (`PurchaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `CustomerID` INT(10) NULL,
  `CustomerFirstName` VARCHAR(255) NULL,
  `CustomerLastName` VARCHAR(255) NULL,
  `CustomerAddress` VARCHAR(255) NULL,
  `CustomerEmail` VARCHAR(255) NULL,
  `CustomerPhone` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OutgoingOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OutgoingOrder` (
  `OrderID` INT(10) NULL,
  `ISBN` INT(13) NOT NULL,
  `CustomerID` INT(10) NOT NULL,
  `DatePlaced` DATE NULL,
  `ShippingAddress` VARCHAR(255) NULL,
  `OrderStatus` VARCHAR(255) NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_OutgoingOrder_Customers1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_OutgoingOrder_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OutgoingOrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OutgoingOrderItem` (
  `ISBN` INT(13) NOT NULL,
  `OrderID` INT(10) NOT NULL,
  `CustomerID` INT(10) NOT NULL,
  `Quantity` INT(10) NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_OutgoingOrderItem_Customers1_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_OutgoingOrderItem_Books1_idx` (`ISBN` ASC) VISIBLE,
  INDEX `fk_OutgoingOrderItem_OutgoingOrder1_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_OutgoingOrderItem_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OutgoingOrderItem_Books1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `mydb`.`Books` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OutgoingOrderItem_OutgoingOrder1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`OutgoingOrder` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
